#Name of the world that the plugin should be active in.
mainWorld: world
fullMoonAngryWolves: true

#Prevents mob spawners from spawning any mobs when the XP multiplier is greater than 1.
#This also allows more mobs to spawn on the surface at night
preventSpawnerXP: true

#Enable Charged Creepers spawn (1 per "chargedChance") when damage multiplier is greater than 1.
#Set chargedChance to 1 for all charged creepers.
enableChargedCreepers: true
chargedChance: 10

###Phase Configuration###

#Master Switch to enable or disable the XP and damage multipliers based on the phase of the moon.
#Essentially disables most functionality of this plugin
enablePhaseModifiers: true

#Night start and end time (in ticks.) Default, nightStarts: 13000; nightEnds: 23000) Must be in the range of [0,24000]
nightStarts: 13000
nightEnds: 23000

#Set Phase multipliers
#Phase0 is the full moon and phase 4 is the new moon
phase0:
  phaseDmg: 2
  phaseXP: 2.5

phase1:
  phaseDmg: 1
  phaseXP: 1

phase2:
  phaseDmg: 1
  phaseXP: 1

phase3:
  phaseDmg: 1
  phaseXP: 1

#New Moon
phase4:
  phaseDmg: 1
  phaseXP: 1

phase5:
  phaseDmg: 1
  phaseXP: 1

phase6:
  phaseDmg: 1.2
  phaseXP: 1.2

phase7:
  phaseDmg: 1.5
  phaseXP: 1.5
