main: com.minecraftport.moonphases.main
version: '${project.version}'
name: MoonPhases
description: Tells the player what phase the moon is in.
author: SDDJ
commands:
  phase:
    description: Tells the player the current moon's phase.